installjars:
	mvn install:install-file \
		-Dfile=./lib/JOGLUTILS/JOGLUTILS.jar \
		-DgroupId=net.java.joglutils \
		-DartifactId=joglutils \
		-Dversion=1.2008 \
		-Dpackaging=jar \
		-DgeneratePom=true