installjars:
	# mvn install:install-file \
	# 	-Dfile=./lib/Beanshell/bsh-2.0b4_seg.jar \
	# 	-DgroupId=org.apache-extras.beanshell \
	# 	-DartifactId=bsh \
	# 	-Dversion=local_2.0b4 \
	# 	-Dpackaging=jar \
	# 	-DgeneratePom=true
	# mvn install:install-file \
	# 	-Dfile=./lib/Jama/Jama-1.0.2.jar \
	# 	-DgroupId=gov.nist.math \
	# 	-DartifactId=jama \
	# 	-Dversion=local_1.0.2 \
	# 	-Dpackaging=jar \
	# 	-DgeneratePom=true
	# mvn install:install-file \
	# 	-Dfile=./lib/Java_Media_Framework/jmf.jar \
	# 	-DgroupId=javax.media \
	# 	-DartifactId=jmf \
	# 	-Dversion=local_2.1.x \
	# 	-Dpackaging=jar \
	# 	-DgeneratePom=true
	mvn install:install-file \
		-Dfile=./lib/JOGL/jogl.jar \
		-DgroupId=org.jogamp.jogl \
		-DartifactId=jogl \
		-Dversion=local_1.1.2 \
		-Dpackaging=jar \
		-DgeneratePom=true
	mvn install:install-file \
		-Dfile=./lib/JOGL/gluegen-rt.jar \
		-DgroupId=org.jogamp.gluegen \
		-DartifactId=gluegen-rt \
		-Dversion=local_1.1.2 \
		-Dpackaging=jar \
		-DgeneratePom=true
	mvn install:install-file \
		-Dfile=./lib/JOGLUTILS/JOGLUTILS.jar \
		-DgroupId=net.java.joglutils \
		-DartifactId=joglutils \
		-Dversion=1.2008 \
		-Dpackaging=jar \
		-DgeneratePom=true
	mvn install:install-file \
		-Dfile=./lib/Netscape_JavaScript/plugin.jar \
		-DgroupId=netscape \
		-DartifactId=javascript \
		-Dversion=1.2007 \
		-Dpackaging=jar \
		-DgeneratePom=true
	mvn install:install-file \
		-Dfile=./lib/worldwind/worldwind.jar \
		-DgroupId=gov.nasa \
		-DartifactId=worldwind \
		-Dversion=local_0.6.134.11486 \
		-Dpackaging=jar \
		-DgeneratePom=true
	mvn install:install-file \
		-Dfile=./lib/worldwind/worldwind-2.2.1.jar \
		-DgroupId=gov.nasa \
		-DartifactId=worldwind \
		-Dversion=local_2.2.1 \
		-Dpackaging=jar \
		-DgeneratePom=true
	mvn install:install-file \
		-Dfile=./lib/worldwind/worldwindx-2.2.1.jar \
		-DgroupId=gov.nasa \
		-DartifactId=worldwindx \
		-Dversion=local_2.2.1 \
		-Dpackaging=jar \
		-DgeneratePom=true
